create or replace procedure SORTE.SANDBOX.SP_PAGAMENTOS2_LOAD()
returns int not null
language sql
as
$$

BEGIN

MERGE INTO SORTE.SANDBOX.PAGAMENTOS2 AS TARGET 
USING (
    select 
    $1:"CodigoPagamento"::INTEGER as CodigoPagamento,
    $1:"NumeroParcela"::INTEGER as NumeroParcela,
    $1:"CodigoUsuario"::INTEGER as CodigoUsuario,
    $1:"Data"::DATETIME as Data,
    $1:"Valor"::FLOAT as Valor,
    $1:"TipoCompra"::STRING as TipoCompra,
    $1:"Situacao"::STRING as Situacao,
    $1:"Tipo"::STRING as Tipo,
    $1:"DataHoraExpiracao"::DATETIME as DataHoraExpiracao,
    $1:"IP"::STRING as IP,
    $1:"DataConf"::DATETIME as DataConf,
    $1:"LoginConf"::STRING as LoginConf,
    $1:"CodigoMidia"::INTEGER as CodigoMidia,
    $1:"idPublicacao"::STRING as idPublicacao,
    $1:"Revisita"::STRING as Revisita,
    $1:"ValorProduto"::FLOAT as ValorProduto,
    $1:"ValorFrete"::FLOAT as ValorFrete,
    $1:"ValorServico"::FLOAT as ValorServico,
    $1:"ValorCredito"::FLOAT as ValorCredito,
    $1:"ValorDesconto"::FLOAT as ValorDesconto,
    $1:"ValorPagar"::FLOAT as ValorPagar,
    $1:"SituacaoPedido"::STRING as SituacaoPedido,
    $1:"CodigoMidiaRecompra"::INTEGER as CodigoMidiaRecompra,
    $1:"CodigoPagamentoDe"::INTEGER as CodigoPagamentoDe,
    $1:"CodigoSite"::INTEGER as CodigoSite,
    $1:"CodigoPagamentoCredito"::INTEGER as CodigoPagamentoCredito,
    $1:"ValorTarifa"::FLOAT as ValorTarifa,
    $1:"NumeroLotePMSP"::INTEGER as NumeroLotePMSP,
    $1:"ValidadeDe"::DATETIME as ValidadeDe,
    $1:"ValidadeAte"::DATETIME as ValidadeAte,
    $1:"GoogleCanc"::STRING as GoogleCanc,
    $1:"NumeroConcursoDe"::INTEGER as NumeroConcursoDe,
    $1:"NumeroConcursoAte"::INTEGER as NumeroConcursoAte,
    $1:"QuantidadeConcursos"::INTEGER as QuantidadeConcursos,
    $1:"ValorTarifaBancaria"::INTEGER as ValorTarifaBancaria,
    $1:"Internacional"::STRING as Internacional,
    $1:"LS_Distribuido"::STRING as LS_Distribuido,
    $1:"Cupom"::STRING as Cupom,
    $1:"Semestral"::STRING as Semestral,
    $1:"Periodos"::INTEGER as Periodos,
    $1:"ExcedeuLimite"::STRING as ExcedeuLimite,
    $1:"DataLiquidacao"::DATETIME as DataLiquidacao,
    $1:"DataHoraVencimento"::DATETIME as DataHoraVencimento,
    $1:"MotivoCanc"::INTEGER as MotivoCanc,
    $1:"ValorDolar"::FLOAT as ValorDolar,
    $1:"ValorTarifaDolar"::FLOAT as ValorTarifaDolar,
    $1:"Device"::STRING as Device,
    $1:"CupomLS"::STRING as CupomLS,
    $1:"CodigoOrigemSite"::STRING as CodigoOrigemSite,
    $1:"NewUser"::STRING as NewUser,
    $1:"MotivoCancAdm"::INTEGER as MotivoCancAdm,
    $1:"DescMotivoCancAdm"::STRING as DescMotivoCancAdm,
    $1:"ValorDebitoCredito"::FLOAT as ValorDebitoCredito,
    $1:"ValorDebitoPremio"::FLOAT as ValorDebitoPremio,
    $1:"DataAntecipa"::DATETIME as DataAntecipa,
    $1:"LoginAntecipa"::STRING as LoginAntecipa,
    $1:"ValorProrata"::FLOAT as ValorProrata,
    $1:"ValorTaxaGateway"::FLOAT as ValorTaxaGateway,
    $1:"Email"::STRING as Email,
    $1:"PontosFidelizacao"::INTEGER as PontosFidelizacao
from @azure_stage/Pagamentos2.json
) AS SOURCE 
ON (SOURCE.CodigoPagamento = TARGET.CodigoPagamento AND SOURCE.NumeroParcela = TARGET.NumeroParcela)
WHEN MATCHED THEN 
    UPDATE SET 
        TARGET.CodigoPagamento = SOURCE.CodigoPagamento,
        TARGET.NumeroParcela = SOURCE.NumeroParcela,
        TARGET.CodigoUsuario = SOURCE.CodigoUsuario,
        TARGET.Data = SOURCE.Data,
        TARGET.Valor = SOURCE.Valor,
        TARGET.TipoCompra = SOURCE.TipoCompra,
        TARGET.Situacao = SOURCE.Situacao,
        TARGET.Tipo = SOURCE.Tipo,
		TARGET.DataHoraExpiracao = SOURCE.DataHoraExpiracao,
        TARGET.IP = SOURCE.IP,
        TARGET.DataConf = SOURCE.DataConf,
        TARGET.LoginConf = SOURCE.LoginConf,
        TARGET.CodigoMidia = SOURCE.CodigoMidia,
        TARGET.idPublicacao = SOURCE.idPublicacao,
        TARGET.Revisita = SOURCE.Revisita,
        TARGET.ValorProduto = SOURCE.ValorProduto,
		TARGET.ValorFrete = SOURCE.ValorFrete,
        TARGET.ValorServico = SOURCE.ValorServico,
        TARGET.ValorCredito = SOURCE.ValorCredito,
        TARGET.ValorDesconto = SOURCE.ValorDesconto,
        TARGET.ValorPagar = SOURCE.ValorPagar,
        TARGET.SituacaoPedido = SOURCE.SituacaoPedido,
        TARGET.CodigoMidiaRecompra = SOURCE.CodigoMidiaRecompra,
        TARGET.CodigoPagamentoDe = SOURCE.CodigoPagamentoDe,
		TARGET.CodigoSite = SOURCE.CodigoSite,
        TARGET.CodigoPagamentoCredito = SOURCE.CodigoPagamentoCredito,
        TARGET.ValorTarifa = SOURCE.ValorTarifa,
        TARGET.NumeroLotePMSP = SOURCE.NumeroLotePMSP,
        TARGET.ValidadeDe = SOURCE.ValidadeDe,
        TARGET.ValidadeAte = SOURCE.ValidadeAte,
        TARGET.GoogleCanc = SOURCE.GoogleCanc,
        TARGET.NumeroConcursoDe = SOURCE.NumeroConcursoDe,
		TARGET.NumeroConcursoAte = SOURCE.NumeroConcursoAte,
        TARGET.QuantidadeConcursos = SOURCE.QuantidadeConcursos,
        TARGET.ValorTarifaBancaria = SOURCE.ValorTarifaBancaria,
        TARGET.Internacional = SOURCE.Internacional,
        TARGET.LS_Distribuido = SOURCE.LS_Distribuido,
        TARGET.Cupom = SOURCE.Cupom,
        TARGET.Semestral = SOURCE.Semestral,
        TARGET.Periodos = SOURCE.Periodos,
		TARGET.ExcedeuLimite = SOURCE.ExcedeuLimite,
        TARGET.DataLiquidacao = SOURCE.DataLiquidacao,
        TARGET.DataHoraVencimento = SOURCE.DataHoraVencimento,
        TARGET.MotivoCanc = SOURCE.MotivoCanc,
        TARGET.ValorDolar = SOURCE.ValorDolar,
        TARGET.ValorTarifaDolar = SOURCE.ValorTarifaDolar,
        TARGET.Device = SOURCE.Device,
        TARGET.CupomLS = SOURCE.CupomLS,
		TARGET.CodigoOrigemSite = SOURCE.CodigoOrigemSite,
        TARGET.NewUser = SOURCE.NewUser,
        TARGET.MotivoCancAdm = SOURCE.MotivoCancAdm,
        TARGET.DescMotivoCancAdm = SOURCE.DescMotivoCancAdm,
		TARGET.ValorDebitoCredito = SOURCE.ValorDebitoCredito,
        TARGET.ValorDebitoPremio = SOURCE.ValorDebitoPremio,
        TARGET.DataAntecipa = SOURCE.DataAntecipa,
        TARGET.LoginAntecipa = SOURCE.LoginAntecipa,
        TARGET.ValorProrata = SOURCE.ValorProrata,
        TARGET.ValorTaxaGateway = SOURCE.ValorTaxaGateway,
        TARGET.Email = SOURCE.Email,
        TARGET.PontosFidelizacao = SOURCE.PontosFidelizacao
WHEN NOT MATCHED THEN 
    INSERT (CODIGOPAGAMENTO, 
			NUMEROPARCELA, 
			CODIGOUSUARIO, 
			DATA, 
			VALOR, 
			TIPOCOMPRA, 
			SITUACAO, 
			TIPO,
			DATAHORAEXPIRACAO,
			IP,
			DATACONF,
			LOGINCONF,
			CODIGOMIDIA,
			IDPUBLICACAO,
			REVISITA, 
			VALORPRODUTO, 
			VALORFRETE, 
			VALORSERVICO, 
			VALORCREDITO, 
			VALORDESCONTO, 
			VALORPAGAR, 
			SITUACAOPEDIDO,
			CODIGOMIDIARECOMPRA,
			CODIGOPAGAMENTODE,
			CODIGOSITE,
			CODIGOPAGAMENTOCREDITO,
			VALORTARIFA,
			NUMEROLOTEPMSP,
			VALIDADEDE, 
			VALIDADEATE, 
			GOOGLECANC, 
			NUMEROCONCURSODE, 
			NUMEROCONCURSOATE, 
			QUANTIDADECONCURSOS, 
			VALORTARIFABANCARIA, 
			INTERNACIONAL,
			LS_DISTRIBUIDO,
			CUPOM,
			SEMESTRAL,
			PERIODOS,
			EXCEDEULIMITE,
			DATALIQUIDACAO,
			DATAHORAVENCIMENTO, 
			MOTIVOCANC, 
			VALORDOLAR, 
			VALORTARIFADOLAR, 
			DEVICE, 
			CUPOMLS, 
			CODIGOORIGEMSITE, 
			NEWUSER,
			MOTIVOCANCADM,
			DESCMOTIVOCANCADM,
			VALORDEBITOCREDITO,
			VALORDEBITOPREMIO,
			DATAANTECIPA,
			LOGINANTECIPA,
			VALORPRORATA,
			VALORTAXAGATEWAY,
			EMAIL,
			PONTOSFIDELIZACAO)
        VALUES(SOURCE.CODIGOPAGAMENTO, 
			SOURCE.NUMEROPARCELA, 
			SOURCE.CODIGOUSUARIO, 
			SOURCE.DATA, 
			SOURCE.VALOR, 
			SOURCE.TIPOCOMPRA, 
			SOURCE.SITUACAO, 
			SOURCE.TIPO,
			SOURCE.DATAHORAEXPIRACAO,
			SOURCE.IP,
			SOURCE.DATACONF,
			SOURCE.LOGINCONF,
			SOURCE.CODIGOMIDIA,
			SOURCE.IDPUBLICACAO,
			SOURCE.REVISITA, 
			SOURCE.VALORPRODUTO, 
			SOURCE.VALORFRETE, 
			SOURCE.VALORSERVICO, 
			SOURCE.VALORCREDITO, 
			SOURCE.VALORDESCONTO, 
			SOURCE.VALORPAGAR, 
			SOURCE.SITUACAOPEDIDO,
			SOURCE.CODIGOMIDIARECOMPRA,
			SOURCE.CODIGOPAGAMENTODE,
			SOURCE.CODIGOSITE,
			SOURCE.CODIGOPAGAMENTOCREDITO,
			SOURCE.VALORTARIFA,
			SOURCE.NUMEROLOTEPMSP,
			SOURCE.VALIDADEDE, 
			SOURCE.VALIDADEATE, 
			SOURCE.GOOGLECANC, 
			SOURCE.NUMEROCONCURSODE, 
			SOURCE.NUMEROCONCURSOATE, 
			SOURCE.QUANTIDADECONCURSOS, 
			SOURCE.VALORTARIFABANCARIA, 
			SOURCE.INTERNACIONAL,
			SOURCE.LS_DISTRIBUIDO,
			SOURCE.CUPOM,
			SOURCE.SEMESTRAL,
			SOURCE.PERIODOS,
			SOURCE.EXCEDEULIMITE,
			SOURCE.DATALIQUIDACAO,
			SOURCE.DATAHORAVENCIMENTO, 
			SOURCE.MOTIVOCANC, 
			SOURCE.VALORDOLAR, 
			SOURCE.VALORTARIFADOLAR, 
			SOURCE.DEVICE, 
			SOURCE.CUPOMLS, 
			SOURCE.CODIGOORIGEMSITE, 
			SOURCE.NEWUSER,
			SOURCE.MOTIVOCANCADM,
			SOURCE.DESCMOTIVOCANCADM,
			SOURCE.VALORDEBITOCREDITO,
			SOURCE.VALORDEBITOPREMIO,
			SOURCE.DATAANTECIPA,
			SOURCE.LOGINANTECIPA,
			SOURCE.VALORPRORATA,
			SOURCE.VALORTAXAGATEWAY,
			SOURCE.EMAIL,
			SOURCE.PONTOSFIDELIZACAO);
            
END;
$$
;
