
BEGIN
CREATE OR REPLACE TABLE SORTE.RAW_SF.DEZENASSORT AS 
SELECT NICKNAME AS LOTERIA, CODIGOLOTERIA, VALUE AS RESULTADO, COUNT(*) AS FREQ
FROM (
SELECT      RC.RESULTADO, C.CODIGOLOTERIA, L.NICKNAME
FROM        SORTE.RAW_SITESOL.RESULTADOSCONCURSOS RC
INNER JOIN  SORTE.RAW_SITESOL.CONCURSOS C 
ON          C.CodigoConcurso = RC.CodigoConcurso
INNER JOIN  SORTE.RAW_SITESOL.LOTERIAS L
ON          C.CodigoLoteria = L.CodigoLoteria
WHERE       C.CodigoLoteria NOT IN (5,6,7)
AND         DATEDIFF('day',C.DataSorteio, CURRENT_DATE()) <= 30
) X, LATERAL SPLIT_TO_TABLE(RESULTADO, ' ') WHERE CAST(TRIM(VALUE) AS VARCHAR) NOT IN ('1','2','3','4','5','6', '-') GROUP BY NICKNAME, CODIGOLOTERIA, VALUE order by 4 desc, 2 asc;

CREATE OR REPLACE TABLE SORTE.RAW_SF.DEZENAS_MAIS_SORTEADAS AS
SELECT LOTERIA, DEZENAS FROM (
SELECT CODIGOLOTERIA, LOTERIA, 
       LISTAGG(RESULTADO, ' - ') WITHIN GROUP (ORDER BY FREQ DESC) AS DEZENAS 
FROM (
  SELECT CODIGOLOTERIA,LOTERIA, RESULTADO, FREQ, ROW_NUMBER() OVER (PARTITION BY LOTERIA ORDER BY FREQ DESC) AS RN
  FROM SORTE.RAW_SF.DEZENASSORT
) 
WHERE RN <= 3
GROUP BY CODIGOLOTERIA,LOTERIA
UNION ALL
SELECT
    13,
    'TT_MAIS',
    MAISSORTEADA
FROM (
SELECT TOP 1 max(RESULTADO) AS MAISSORTEADA, SUM(FREQ) FROM SORTE.RAW_SF.DEZENASSORT GROUP BY RESULTADO ORDER BY 2 DESC 
  ) MS
UNION ALL
SELECT
    14,
    'TT_PAR',
    MAISSORTEADA
FROM (
SELECT TOP 1 max(RESULTADO) AS MAISSORTEADA, SUM(FREQ) FROM SORTE.RAW_SF.DEZENASSORT WHERE RESULTADO % 2 = 0 GROUP BY RESULTADO ORDER BY 2 DESC 
  ) MSP
UNION ALL
SELECT
    15,
    'TT_IMPAR',
    MAISSORTEADA
FROM (
SELECT TOP 1 max(RESULTADO) AS MAISSORTEADA, SUM(FREQ) FROM SORTE.RAW_SF.DEZENASSORT WHERE RESULTADO % 2 = 1 GROUP BY RESULTADO ORDER BY 2 DESC 
  ) MSI
UNION ALL
SELECT    6, 'LT' AS LOTERIA, 
        CONCAT('Time 1: ',media_qtdc4,'% / Empate: ',media_qtdc2,'% / Time 2: ',media_qtdc1,'%.') AS Dezenas 
FROM (
    SELECT    ROUND(AVG(CAST(RC.QTDC4 AS FLOAT))/14 * 100, 2) AS media_qtdc4, 
            (100 - ROUND(AVG(CAST(RC.QTDC4 AS FLOAT))/14 * 100, 2) - ROUND(AVG(CAST(RC.QTDC1 AS FLOAT))/14 * 100, 2)) AS media_qtdc2,
            ROUND(AVG(CAST(RC.QTDC1 AS FLOAT))/14 * 100, 2) AS media_qtdc1
    FROM (
        SELECT    RC.RESULTADO,
                LENGTH(RC.RESULTADO) AS COLUNA_LEN,
                (LENGTH(Resultado) - LENGTH(REPLACE(Resultado, '1', ''))) AS QTDC1,
                (LENGTH(Resultado) - LENGTH(REPLACE(Resultado, '2', ''))) AS QTDC2,
                (LENGTH(Resultado) - LENGTH(REPLACE(Resultado, '4', ''))) AS QTDC4
        FROM sorte.RAW_SITESOL.RESULTADOSCONCURSOS RC
        JOIN sorte.RAW_SITESOL.Concursos C
            ON RC.CODIGOCONCURSO = C.CODIGOCONCURSO
            AND C.CODIGOLOTERIA = 6
        WHERE DATEDIFF('day',C.DataSorteio, CURRENT_DATE()) <= 30
    ) AS RC
) order by CODIGOLOTERIA ASC
) FINAL;

END;
